// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanDictionary.DataAccess.Data;

namespace UrbanDictionary.DataAccess.Migrations
{
    [DbContext(typeof(UrbanDictionaryDBContext))]
    [Migration("20200412120358_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.UserSavedWord", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("SavedWordId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "SavedWordId");

                    b.HasIndex("SavedWordId");

                    b.ToTable("UserSavedWords");
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DislikesCount")
                        .HasColumnType("int");

                    b.Property<string>("Example")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 10L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 11L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 12L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 13L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 14L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 15L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 16L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 17L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 18L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 19L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 20L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 21L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 22L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 23L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 24L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 25L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 26L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 27L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 28L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 29L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 30L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 31L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 32L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 33L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 34L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 35L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 36L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 37L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 38L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 39L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 40L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 41L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 42L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 43L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 44L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 45L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 46L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 47L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 48L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 49L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 50L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 51L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 52L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 53L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 54L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 55L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 56L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 57L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 58L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 59L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 60L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 61L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 62L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 63L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 64L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 65L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 66L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 67L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 68L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 69L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 70L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 71L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 72L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 73L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 74L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 75L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 76L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 77L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 78L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 79L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 80L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 81L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 82L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName6",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 83L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 84L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 85L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 86L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName2",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 87L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 88L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName3",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 89L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 90L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 91L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 92L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName5",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 93L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 94L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName1",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 95L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 96L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName0",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 97L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName4",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 98L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName8",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 99L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName9",
                            WordStatus = 0
                        },
                        new
                        {
                            Id = 100L,
                            AuthorId = "default",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Definition = "Default word definition",
                            DislikesCount = 31,
                            Example = "Default word example",
                            LikesCount = 100,
                            Name = "DefaultWordName7",
                            WordStatus = 0
                        });
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.WordTag", b =>
                {
                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.HasKey("WordId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("WordTags");
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "default",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "default",
                            Email = "email@default.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "EMAIL@DEFAULT.COM",
                            NormalizedUserName = "DEFAULTUSERNAME",
                            PasswordHash = "defaultHash",
                            PhoneNumber = "000000000",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "default",
                            TwoFactorEnabled = false,
                            UserName = "DefaultUserName"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.UserSavedWord", b =>
                {
                    b.HasOne("UrbanDictionary.DataAccess.Entities.Word", "SavedWord")
                        .WithMany("UserSavedWords")
                        .HasForeignKey("SavedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanDictionary.DataAccess.Entities.User", "User")
                        .WithMany("UserSavedWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.Word", b =>
                {
                    b.HasOne("UrbanDictionary.DataAccess.Entities.User", "Author")
                        .WithMany("CreatedWords")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("UrbanDictionary.DataAccess.Entities.WordTag", b =>
                {
                    b.HasOne("UrbanDictionary.DataAccess.Entities.Tag", "Tag")
                        .WithMany("WordTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanDictionary.DataAccess.Entities.Word", "Word")
                        .WithMany("WordTags")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
